### ISSUE TITLE
Ruby Style: Lot of space  also not maintain ruby style or rails best practices 

### ISSUE THREAD

**Issue by rajcybage** [himadriganguly/partyup#1]
Good App but

Use rubocop/ rails best practice / metric fu to check the offences 

Lastly use code climate and get a badge

**Comment by rajcybage** [comment]
```
Favourite.where("vendor_id=?",current_vendor.id).order('created_at DESC').page(params[:page]).per(10)

```

in controller :)

**Comment by himadriganguly** [comment]
Thank you for your feedback. I tried to maintain the Ruby Style as much as I can. Although I developed this as the first version as a Beta Version there might be some mistakes, currently not maintaining the project. I uploaded it if this code might be helpful to someone else.

Thank you.

**Comment by himadriganguly** [comment]
I am closing this issue.

Thank you.
